services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin'

    ports:
      - "3306:3306"

    expose:
      - '3306'

    volumes:
      - /Users/leonardomerloprimieri/Documents/development/personal/python/advanced-flask-api/mysql:/var/lib/mysql